export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOGOUT = "LOGOUT";
export const GET_USERS = "GET_USERS";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const SAVE_QUESTION = "SAVE_QUESTION";
export const SAVE_ANSWERS_QUESTION = "SAVE_ANSWERS_QUESTION";
export const SAVE_USER_QUESTION = "SAVE_USER_QUESTION";
export const SAVE_USER_ANSWERS = "SAVE_USER_ANSWERS";
